### ISSUE TITLE
feat(lang): Add React support

### ISSUE THREAD

**Issue by Namchee** [Namchee/dependent#20]
## Overview

We need to support React, a declarative JavaScript UI library. The reason for this is because React is immensely popular and heavily used in front-end projects. 

The support should include both `jsx` and `tsx`, since TypeScript support itself has been implemented.

### Reference

[JSX Reference](https://reactjs.org/docs/introducing-jsx.html)

### Implementation Ideas

We can use [acorn-jsx](https://github.com/acornjs/acorn-jsx) to parse `jsx`
As for `tsx`, it can be parsed with [TypeScript Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)

### Tasks

- [x] Implement `jsx` parser b0d29382dfde1229c18b2de79740e6fdc88d9ae0
- [x] Implement `tsx` parser b9ffd8e54d7483823358732ed82ef8b1dd70d83e
- [x] Test the functionalities 25e332f538cc1561524a71fff5a15208c1958229
