### ISSUE TITLE
docs: Add contribution documentation

### ISSUE THREAD

**Issue by Namchee** [Namchee/dependent#4]
## Overview

Currently, this project lacks any guidance for anyone to contribute. We need to write better documentation for contributors especially since the parsers are now easily extendable to support more languages.

### Tasks

- [x] Create issue template a7d82dfbae14017451be418cf11fed9ca44838c0
- [x] Create pull request template 964e792b71b92c29c85c9df6c8d2c28ee03e645b
- [x] Write better documentation about CLI options and arguments fbc1e41336aa83d8f79217e2916396aa2103876e
- [x] Write contribution guidelines 63a215a7de9018776517b58de30d9354c2216ada
- [x] Write documentation about parser contribution 040a5642e81d0dc5faa40ca002c27ab372efeac2

**Comment by Namchee** [comment]
Issue template is created via #5

**Comment by Namchee** [comment]
Pull request template is created via #7

**Comment by Namchee** [comment]
Documentation is rewritten via #14

**Comment by Namchee** [comment]
Contributing guidelines is added via #16

**Comment by Namchee** [comment]
Parser contributing guidelines is added via #18
