### ISSUE TITLE
feat: Structured reporting

### ISSUE THREAD

**Issue by Namchee** [Namchee/dependent#41]
## Overview

We need to do a restructure to how the results are being reported. Right now, it's too random, especially since the API is changed to asynchronous calls which don't guarantee any order at all.

A good start would be something like -> group JS files together and order them based on the depth while grouping TS files together on a different group.

### Task List

- [x] Design a better-structured result reporting
- [x] Implement the features
- [x] Test the features
